Sweets/Models/Flavor.cs
using System.Collections.Generic;

namespace Sweets.Models
{
    public class Flavor
    {
        public Flavor()
        {
            this.JoinEntities = new HashSet<TreatFlavor>();
        }

        public int FlavorId { get; set; }
        public string FlavorName { get; set; }
        public virtual ICollection<TreatFlavor> JoinEntities { get; set; }
    }
}

Sweets/Controllers/FlavorController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Sweets.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
namespace Sweets.Controllers  
{
    [Authorize]
   public class FlavorsController : Controller
  {
    private readonly SweetsContext _db;

    public FlavorsController(SweetsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
        var thisFlavor = _db.Flavors
            .Include(flavor => flavor.JoinEntities)
            .ThenInclude(join => join.Treat)
            .FirstOrDefault(flavor => flavor.FlavorId == id);
        return View(thisFlavor);
    }

    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId ==id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName", "TreatRating", "TreatInstruction");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor, int TreatId)
    {
      if (TreatId !=0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
     public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId !=0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId }); 
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.TreatFlavor.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Sweets/Controllers/TreatController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Sweets.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
namespace Seets.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly SweetsContext _db;
    private readonly UserManager<ApplicationUser> _userManager; 

    public TreatsController(UserManager<ApplicationUser> userManager, SweetsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        var userTreats = _db.Treats.Where(entry => entry.User.Id == currentUser.Id).ToList();
        return View(userTreats);
    }

    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat, int FlavorId, string Name)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      _db.SaveChanges();
      if (FlavorId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
          .Include(treat => treat.JoinEntities)
          .ThenInclude(join => join.Flavor)
          .FirstOrDefault(treat => treat.TreatId == id);
         
          if (thisTreat == null)
    {
        return NotFound();
    }
      return View(thisTreat);
    }
    
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
   {
    var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    
    if (thisTreat == null)
    {
        return NotFound(); // Return a 404 Not Found response
    }

    // Populate the SelectList with Flavor data
    var flavors = _db.Flavors.ToList();
    ViewBag.FlavorId = new SelectList(flavors, "FlavorId", "FlavorName");

    return View(thisTreat);
}
    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      if (FlavorId !=0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { FlavorId = FlavorId, TreatId = treat.TreatId }); 
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.TreatFlavor.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
   
  }
}

Sweets/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@using Sweets.Models;
@model Sweets.Models.Flavor

<h2>Add a Treat</h2>

<h4>Add a Treat to this Flavor: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select Treat")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Save" class="fancyBtn" />
}

<p class="fancyBtn">@Html.ActionLink("Back to list", "Index")</p>

Sweets/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model Sweets.Models.Flavor

<h4>Add a flavor</h4>
<hr />
<br>

@using (Html.BeginForm())
{
  <p>Flavor name:
  @Html.TextBoxFor(model => model.FlavorName, new { @class = "form-control", placeholder="Required", required="required", style="width: 300px;"})</p>


  <br>
  <p><input type="submit" value="Save" class="btn btn-default" /></p>
}
<hr />
<br>
<h5>@Html.ActionLink("Back to flavors", "Index")</h5>

Sweets/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Sweets.Models.Flavor

<h2>Are you sure you want to delete @Html.DisplayFor(model => model.FlavorName)?</h2>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn"/>
}
<hr />
<br>
<h5>@Html.ActionLink("Back to flavors", "Index")</h5>

Sweets/Views/Flavors/Details.cshtml
@{
    Layout = "_Layout";
}

@model Sweets.Models.Flavor  

<h2>flavor details</h2>  

<hr />

<h3>@Html.DisplayFor(model => model.FlavorName)</h3>  

<h4>treats with this flavor:</h4> 
@if(@Model.JoinEntities.Count == 0)
{
    <p>this flavor is not used in any treats</p>  
}
<ul>
    @foreach (var join in Model.JoinEntities)
    {
        <li>@Html.ActionLink($"{join.Treat.Name}", "Details", "Treats", new {id = join.Treat.TreatId})</li>  
        @using (Html.BeginForm("DeleteTreat", "Flavors"))  
        {
            @Html.Hidden("joinId", @join.TreatFlavorId)  
            <input type="submit" value="remove" />
        }
    }
</ul>

<ul class="menu-links">
    <li>@Html.ActionLink("edit flavor", "Edit", new { id = Model.FlavorId })</li>  
    <li>@Html.ActionLink("delete this flavor", "Delete", new { id = Model.FlavorId })</li>  
    <li>@Html.ActionLink("add a treat with this flavor", "AddTreat", new {id = Model.FlavorId })</li>  
    <li>@Html.ActionLink("back to flavor inventory", "Index")</li> 
</ul>

Sweets/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Sweets.Models.Flavor

<h2>Edit</h2>

<h4>Edit this flavor: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.FlavorId)
    @Html.EditorFor(model => model.FlavorId)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Sweets/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using Sweets.Models;

<h1>Tags</h1>

@if (@Model.Count == 0)
{
  <h3>No tags have been added yet!</h3>
} 

@foreach (Flavor flavor in Model)
{
  <li>@Html.ActionLink($"{flavor.FlavorName}", "Details", new { id = flavor.FlavorId })</li>
}

<p>@Html.ActionLink("Add new flavor", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>